### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by pyrokar1993** [in-RET/in.RET-EnSys-open-plan-GUI#5]
Constraints enden in einer fehlerhaften Simulation

Es wird im Backend ein TypeError verursacht

## Log
09:36:55-INFO-[---I-] Adding constraints to the energy system model.
Traceback (most recent call last):
  File "/app/main.py", line 48, in <module>
    ModelBuilder(configfile, dumpfile, workdir, logdir, dumpdir)
  File "/usr/local/lib/python3.10/site-packages/InRetEnsys/modelbuilder.py", line 65, in __init__
    self.BuildEnergySystem(model.energysystem, DumpFile, model.solver, model.solver_verbose, cmdline_opts=cmdline_opts, only_lp=only_lp)
  File "/usr/local/lib/python3.10/site-packages/InRetEnsys/modelbuilder.py", line 150, in BuildEnergySystem
    solph.constraints.emission_limit(om=model, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/oemof/solph/constraints/integral_limit.py", line 28, in emission_limit
    generic_integral_limit(
  File "/usr/local/lib/python3.10/site-packages/oemof/solph/constraints/integral_limit.py", line 123, in generic_integral_limit
    expr=sum(
  File "/usr/local/lib/python3.10/site-packages/oemof/solph/constraints/integral_limit.py", line 124, in <genexpr>
    om.flow[inflow, outflow, t]
TypeError: unsupported operand type(s) for *: '_GeneralVarData' and 'NoneType'

**Comment by pyrokar1993** [comment]
Fehler liegt an der Einlesen des JSON-File, welches nicht mehr die None-Werte Ignoriert --> Entstanden durch pydantic2.0

**Comment by pyrokar1993** [comment]
Transformer überprüfen, hier liegt der fehler.
